package com.clip.domain.user.enums

enum class City {
    SEOUL, INCHEON, DAEGU, GWANGJU, DAEJEON, BUSAN, ULSAN, SEJONG, GEONGI, GANGWONDO, GYEONGSANGBUKDO, GYEONGSANGNAMDO, CHUNGSHEONGBUKDO, CHUNGCHEONGNAMDO, JEOLLABUKDO, JEOLLANAMDO, JEJU
}
